- name: Set Up Ubuntu on EC2 Instance
  hosts: all
  tasks:
    - name: Update all packages
      become: true
      apt:
        upgrade: dist
        force_apt_get: true
        update_cache: true
    - name: 'Install tools, pip3 and nginx'
      become: true
      apt:
        name: '{{ item }}'
        install_recommends: 'yes'
        state: present
      loop:
        - vim
        - wget
        - curl
        - ca-certificates
        - plocate
        - python3-pip
        - nginx
    - block:
        - name: Set up Docker's apt repository
          become: true
          file:
            path: /etc/apt/keyrings
            state: directory
            mode: 493
        - name: Download Docker GPG Key
          become: true
          get_url:
            url: 'https://download.docker.com/linux/ubuntu/gpg'
            dest: /etc/apt/keyrings/docker.asc
            mode: 420
        - name: Add Docker repository
          become: true
          apt_repository:
            repo: >-
              deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc]
              https://download.docker.com/linux/ubuntu {{
              ansible_distribution_release }} stable
            state: present
        - name: Install Docker via apt
          become: true
          apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
              - docker-compose-plugin
            state: present
            update_cache: true
        - name: Add user to group
          become: true
          user:
            name: '{{ ansible_user_id}}'
            groups: docker
            append: 'yes'
